### PR TITLE
add js file and coding for own section

### PR DESCRIPTION
**Pull request by tatsuya167**

### CODE REVIEW

**Comment by wakandajp** [comment]
no JS file 
Did you commit js file?

**Comment by tatsuya167** [comment]
> no JS file
> Did you commit js file?

>Sorry I made a mistake. I added

**Comment by wakandajp** [comment]
- The design in section 3 is supposed to be like the design that James gave us
    - Can you use gradation, instead of image?
    - Every image could have different height. Is this problem considered?
- In JS file, no codes in there. If you want to access Web API, talk to Jun about it.
    - But this JS function can be done after merge this pull request
- Can you merge master branch before pull request?

**Comment by eastend-street** [comment]
There is conflict, please check it.

**Pull request closed without merging**
